### PR TITLE
updated the method signatures to fix the build using new BOOST

### PR DESCRIPTION
**Pull request by shmutalov**

### CODE REVIEW

**Comment by qogecoin-dev** [comment]
Thank you for your pull request. Can you specify the boost version?

**Comment by shmutalov** [comment]
`1.71`

I've built qogecoin under Ubuntu 20.04

**Comment by f04ever** [comment]
Good update! I did the same for building in macOS!

**Comment by qogecoin-dev** [comment]
Builds on Ubuntu 20.04 with boost 1.71 and berkeley-db-4.8.30.
Thank you for your PR  🚀

**Pull request merged**
